[master]
  version = 1
  runner = "s3://ambiata-dispensary-v2/dist/master/master-haskell/linux/x86_64/20171113234252-7750b12/master-haskell-20171113234252-7750b12"
  sha1 = "1dd2df33e187920050114f62aa8de3cdd04fe595"

[global]
  CACHE = "true"

[build.dist-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"

[build.dist-8-0]
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_MASTER"
  HADDOCK_URL = "$AMBIATA_HADDOCK_MASTER_URL"
  GHC_VERSION = "8.0.2"
  CABAL_VERSION = "1.24.0.2"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_MASTER"
  PUBLISH_EXECUTABLES = "box"

[build.branches-7-10]
  GHC_VERSION = "7.10.2"
  CABAL_VERSION = "1.22.4.0"

[build.branches-8-0]
  HADDOCK = "true"
  HADDOCK_S3 = "$AMBIATA_HADDOCK_BRANCHES"
  HADDOCK_URL = "$AMBIATA_HADDOCK_BRANCHES_URL"
  GHC_VERSION = "8.0.2"
  CABAL_VERSION = "1.24.0.2"
  PUBLISH = "true"
  PUBLISH_S3 = "$AMBIATA_ARTEFACTS_BRANCHES"
  PUBLISH_EXECUTABLES = "box"
